services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    env_file: ".env"
    ports:
      - 127.0.0.1:5432:5432
    volumes:
       - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-backend:
    build: .
    restart: unless-stopped
    env_file: ".env"
    command: >
      bash -c "alembic upgrade head
      && --factory cats.web:create_app --host $UVICORN_HOST --port $UVICORN_PORT"
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres:
