services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=defaultdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
       - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    restart: unless-stopped
    environment:
      - POSTGRES_URI=postgresql+psycopg://postgres:postgres@postgres:5432/defaultdb
    command: >
      bash -c "alembic upgrade head
      && uvicorn --factory cats.web:create_app --host 0.0.0.0 --port 8000"
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres:
