[build-system]
requires = ["setuptools>=66.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "cats"
dynamic = ["version"]
description = "Simple api cats"
readme = "README.md"
authors = [
    { name = "Sergey Yavorsky", email = "maclovi.dev@gmail.com" },
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx==0.27.*",
    "uvloop==0.21.*",
    "orjson==3.*",
    "fastapi==0.115.*",
    "uvicorn==0.31.*",
    "httptools==0.6.*",
    "alembic==1.13.*",
    "sqlalchemy==2.*",
    "psycopg[binary]==3.*",
    "dishka==1.*",
    "python-json-logger==2.*",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio",
]
lint = [
    "ruff",
    "bandit",
    "semgrep",
    "codespell",
    #types
    "mypy",
]
dev = ["cats[test,lint]"]

[project.urls]
Homepage = "https://github.com/Maclovi/fastapi-template"
Documentation = "https://github.com/Maclovi/fastapi-template/README.md"
Repository = "https://github.com/Maclovi/fastapi-template"
Issues = "https://github.com/Maclovi/fastapi-template/issues"


[tool.pytest.ini_options]
xfail_strict = true
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
markers = ["container"]
filterwarnings = []

[tool.mypy]
exclude = [".venv"]
python_version = "3.10"
strict = true
pretty = true

no_implicit_optional = true
check_untyped_defs = true
show_error_codes = true
implicit_reexport = true
namespace_packages = true
ignore_missing_imports = true

warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true

allow_untyped_calls = true
allow_subclassing_any = true
allow_untyped_decorators = true

disallow_incomplete_defs = true
disallow_any_unimported = false

[tool.ruff]
src = ["src"]
include = ["src/**.py", "tests/**.py"]
target-version = "py310"
line-length = 79
fix = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",      # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "A002",   # https://docs.astral.sh/ruff/rules/raw-string-in-exception/
    "EM101",  # https://docs.astral.sh/ruff/rules/raw-string-in-exception/
    "TRY003", # https://docs.astral.sh/ruff/rules/raise-vanilla-args/
    "COM812", # https://docs.astral.sh/ruff/rules/missing-trailing-comma/
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"src/cats/infrastructure/persistence/alembic/**" = ["ERA001", "INP001"]
"src/cats/application/**" = ["S101"]
"tests/**" = ["S101"]

[lint.isort]
no-lines-before = ["local-folder"]
