"""add conventions

Revision ID: d2bbf63abb2e
Revises: 2c4f4df1942c
Create Date: 2024-10-19 13:23:07.531320

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2bbf63abb2e"
down_revision: str | None = "2c4f4df1942c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("breeds_title_key", "breeds", type_="unique")
    op.create_unique_constraint(op.f("uq_breeds_title"), "breeds", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_breeds_title"), "breeds", type_="unique")
    op.create_unique_constraint("breeds_title_key", "breeds", ["title"])
    # ### end Alembic commands ###
