"""add unique

Revision ID: 553dc0c7ba6b
Revises: 1a24a3d07071
Create Date: 2024-10-06 22:10:13.763318

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "553dc0c7ba6b"
down_revision: str | None = "1a24a3d07071"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "breeds", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("breeds_title_key", "breeds", type_="unique")
    # ### end Alembic commands ###
