name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cpython:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 127.0.0.1:5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key:  ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-uv

      - name: Install Dependencies and library
        if: steps.cache.outputs.cache-hit != 'true'
        run: uv pip install --system .[dev]

      - name: Run ruff
        run: ruff check

      - name: Run mypy
        run: mypy src

      - name: Run bandit
        run: bandit -c pyproject.toml -r cats

      - name: Run Semgrep
        run: semgrep scan --config auto --error

      - name: Run pytest
        run: pytest -q
